apiVersion: v1
kind: Service
metadata:
  name: squid-{{ .Release.Name }}
spec:
  selector:
    app: squid-{{ .Release.Name }}
  type: NodePort
  ports:
  - protocol: TCP
    port: 3128
    targetPort: squid
