apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-{{ .Release.Name }}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-squid-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-squid-{{ .Release.Name }}
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-squid-{{ .Release.Name }}
    spec:
      containers:
      - imagePullPolicy: Always
        name: squid
        image: ubuntu/squid
        ports:
        - name: squid
          expose: true
          protocol: TCP
          containerPort: 3128
          _serviceType: NodePort
        readinessProbe:
          failureThreshold: 3
          successThreshold: 1
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          tcpSocket:
            port: 3128
        livenessProbe:
          failureThreshold: 3
          successThreshold: 1
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          tcpSocket:
            port: 3128
      nodeName: "{{ .Release.Name }}"
