apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tx
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app: {{ .Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ .Release.Name }}-0
  type: ClusterIP
