apiVersion: v1
kind: ConfigMap
metadata:
  name: cfgmap-{{ .Release.Name }}
data:
  {{- range $name, $storage := .Values.storages }}
  {{- range $key, $value := $storage }}
  RCLONE_CONFIG_{{ upper $name }}_{{ upper $key }} : {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.options.fastlist }}
  RCLONE_FAST_LIST: "true"
  {{- end }}
  RCLONE_TRANSFERS: {{ .Values.options.transfers | quote }}
  RCLONE_CHECKERS: {{ .Values.options.checkers | quote }}
  RCLONE_DELETE_BEFORE: "true"
  RCLONE_DRIVE_ACKNOWLEDGE_ABUSE: "true"
  RCLONE_DRIVE_CHUNK_SIZE: 128M
  RCLONE_ONEDRIVE_CHUNK_SIZE: 100M
  RCLONE_PROGRESS: "true"
