apiVersion: batch/v1
kind: Job
metadata:
  name: rclone-{{ .Release.Name }}
spec:
  suspend: {{ .Values.rclone.suspend }}
  template:
    spec:
        containers:
            - name: {{ .Values.rclone.action }}
              image: {{ .Values.image | quote }}
              command:
                - rclone
                - {{ .Values.rclone.action }}
                {{- if not .Values.rclone.debug }}
                - '-vv'
                {{- end }}
                - {{ .Values.rclone.from | quote }}
                - {{ .Values.rclone.to | quote }}
              envFrom:
                - configMapRef:
                    name: cfgmap-{{ .Release.Name }}
              imagePullPolicy: Always
        restartPolicy: Never