apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cfg
data:
  # property-like keys; each key maps to a simple value
  php.ini: |
    upload_max_filesize = 1024M
    post_max_size = 1024M
    max_execution_time = 3600
    max_input_vars = 3000
