apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      volumes:
        - name: cfg
          configMap:
            name: {{ .Release.Name }}-cfg
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
      containers:
        - name: wordpress
          image: {{ .Values.image.wordpress }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: cfg
              mountPath: /usr/local/etc/php/conf.d/user.ini
              subPath: php.ini
            - name: data
              mountPath: /var/www/html
              subPath: web
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-web
        - name: database
          image: {{ .Values.image.database }}
          args: ["--skip-log-bin"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: sql
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-sql
  strategy:
    type: Recreate
