apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-{{ .Release.Name }}
  labels:
    workload.user.cattle.io/workloadselector: app-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: app-{{ .Release.Name }}
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: app-{{ .Release.Name }}
    spec:
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: volume-claim-{{ .Release.Name }}
      containers:
        - name: wordpress
          {{ if .Values.ioncube }}
          image: lttech/wordpress:php7.4-ioncube
          {{ else if .Values.frankenphp }}
          image: lttech/frankenphp:8.3.1
          {{ else }}
          image: lttech/wordpress:php8.1
          {{ end }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: http
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 3
          {{ if .Values.scale }}
          resources:
            requests:
              memory: "{{ mul .Values.scale 512 }}Mi"
              cpu: "{{ mul .Values.scale 250 }}m"
            limits:
              memory: "{{ mul .Values.scale 1 }}Gi"
              cpu: "{{ mul .Values.scale 500 }}m"
          {{ end }}
          volumeMounts:
            - name: data
              {{ if .Values.frankenphp }}
              mountPath: /app/public
              {{ else }}
              mountPath: /var/www/html
              {{ end }}
              subPath: web
        - name: database
          image: mariadb:11.1
          args: ["--skip-log-bin"]
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - healthcheck.sh
                - "--connect"
                - "--innodb_initialized"
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            exec:
              command:
                - healthcheck.sh
                - "--connect"
                - "--innodb_initialized"
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
          {{ if .Values.scale }}
          resources:
            requests:
              memory: "{{ mul .Values.scale 512 }}Mi"
              cpu: "{{ mul .Values.scale 250 }}m"
            limits:
              memory: "{{ mul .Values.scale 1 }}Gi"
              cpu: "{{ mul .Values.scale 500 }}m"
          {{ end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: sql
          envFrom:
            - secretRef:
                name: secret-{{ .Release.Name }}
  strategy:
    type: Recreate
