apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ .Release.Name }}-wordpress
type: Opaque
stringData:
  WORDPRESS_DB_HOST: "127.0.0.1"
  WORDPRESS_DB_NAME: {{ .Release.Name }}
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_PASSWORD: {{ .Values.password }}
  {{ if .Values.debug }}
  WORDPRESS_DEBUG: 'true'
  {{ end }}
  WORDPRESS_CONFIG_EXTRA: |
    {{ if not .Values.update }}
    define( 'WP_AUTO_UPDATE_CORE', false );
    {{ end }}
    {{ if .Values.domain }}
    if($_SERVER['HTTPS'] == 'on') {
      define( 'WP_HOME', 'https://' . $_SERVER['HTTP_HOST']);
      define( 'WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST']);
    } else {
      define( 'WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
      define( 'WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
    }
    {{ end }}