apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sql
type: Opaque
stringData:
  MARIADB_DATABASE: {{ .Release.Name }}
  MARIADB_USER: {{ .Release.Name }}
  MARIADB_PASSWORD: {{ .Values.password }}
  MARIADB_RANDOM_ROOT_PASSWORD: "1"