apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  {{ if .Values.public }}
  type: NodePort
  {{ end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
