apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Release.Name }}
spec:
  selector:
    workload.user.cattle.io/workloadselector: app-{{ .Release.Name }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
