apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-volume
spec:
  capacity:
    storage: {{ .Values.storage }}
  csi:
    driver: driver.longhorn.io
    volumeHandle: {{ .Release.Name }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
