apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: {{ .Release.Name }}
  resources:
    requests:
      storage: {{ .Values.storage }}