apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: volume-{{ .Release.Name }}