apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    io.portainer.kubernetes.application.name: {{ .Release.Name }}
    io.portainer.kubernetes.application.owner: admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
  volumeName: {{ .Release.Name }}
  storageClassName: local-path
  volumeMode: Filesystem