apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: Other
  RCLONE_CONFIG_S3_ENDPOINT: {{ .Values.s3.endpoint }}
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: {{ .Values.s3.key }}
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: {{ .Values.s3.secret }}
  {{- if .Values.options.fastlist }}
  RCLONE_FAST_LIST: "true"
  {{- end }}
  RCLONE_TRANSFERS: "{{ .Values.options.transfers }}"
  RCLONE_CHECKERS: "{{ .Values.options.checkers }}"
  RCLONE_DELETE_BEFORE: "true"
  RCLONE_PROGRESS: "true"
